@startuml
Aluno -- Curso
Curso --* Disciplina
Turma -- Professor
Turma -- Aluno
Turma -- Disciplina
Aluno -- ICurriculo
Aluno -- ICobranca
Disciplina -- Tipo
Turma -- Status

class Curso{
    - nome: String
    - creditos: int
    - disciplinas: List<Disciplina> 
}

interface ICurriculo{
    + gerarCurriculoSemestral(): String
}

interface ICobranca{
    + notificarCobranca(): void
}

class Aluno{
    - curso: Curso
    - turma: Turma
    + matricularDisciplina(Disciplina disciplina): void
    + checarOptativas(): boolean
    + cancelarMatricula(Disciplina disciplina): boolean
}

class Professor{
    - nome: String
    + checarAlunos(Disciplina disciplina): List<Aluno>
}

class Disciplina {
    - cargaHoraria: float
    - tipo: Tipo
    - curso: Curso
    + checarAlunosMatriculados(): List<Aluno>
    + fecharDisciplina(): void
}

enum Tipo {
    - OBRIGATORIA
    - OPTATIVA
}

class Turma {
    - semestre: String
    - ano: Date
    - disciplina: Disciplina
    - professor: Professor
    - status: Status
    - minAlunos: static int = 3
    - maxAlunos: static int = 60
    - alunos: List<Aluno>
    + cancelarTurma(): void
    + adicionarAluno(Aluno aluno): void
    + removerAluno(Aluno aluno): void
}

enum Status {
    - ABERTA
    - FECHADA
    - CANCELADA
    - CONCLUIDA
}

skinparam classAttributeIconSize 0
@enduml
